- name: User configuration
  remote_user: its
  hosts: localhost
  vars_files: ['credentials.yml']
  become: yes
  tasks:
 
 
#
#========================================#
#    User Configuration
#========================================#
 
 
    - name: User its 
      user:
        name: its
        state: present
        update_password: always
        password: "{{ user_default_password }}"
        shell: /bin/bash
